version: '2'
services:
  web:
    build: .
    env_file: docker/.local_env
    hostname: aoll.localdomain
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    command: /sbin/init

  db:
    build: docker/mysql/
    env_file: docker/.local_env
    ports:
      - 3308:3306
    volumes:
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql

  redis:
    image: redis:3.2.4
    ports:
      - 6379:6379